# -*- coding: utf-8 -*-
"""main_ALS copy 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ee3hsl5xN91ldDdZhv0kX5sV80jlmECi
"""


# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob
import os
from datetime import datetime, timezone
import warnings
import zipfile
import shutil
import tempfile
warnings.filterwarnings('ignore')

# Set visualization style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)


# Load all CSV files from dataset folder
data_path = 'dataset/'
csv_files = sorted(glob(os.path.join(data_path, 'label_full_data_part_*.csv')))


# Load and combine all CSV files
df_list = []
for file in csv_files:
    df_temp = pd.read_csv(file)
    df_list.append(df_temp)

# Combine all dataframes
df = pd.concat(df_list, ignore_index=True)


# Display first few rows




# Convert TimePlaced to datetime
df['TimePlaced'] = pd.to_datetime(df['TimePlaced'])

# Extract additional time features
df['Date'] = df['TimePlaced'].dt.date
df['Hour'] = df['TimePlaced'].dt.hour
df['DayOfWeek'] = df['TimePlaced'].dt.day_name()
df['Month'] = df['TimePlaced'].dt.month
df['Year'] = df['TimePlaced'].dt.year

# Statistical summary


# Additional statistics


"""# Data Visualization

"""

# 1. Price Distribution
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Histogram
axes[0].hist(df['Price'], bins=50, edgecolor='black', alpha=0.7)
axes[0].set_xlabel('Price')
axes[0].set_ylabel('Frequency')
axes[0].set_title('Price Distribution')
axes[0].grid(True, alpha=0.3)

# Box plot
axes[1].boxplot(df['Price'], vert=True)
axes[1].set_ylabel('Price')
axes[1].set_title('Price Box Plot')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()



# 2. Top 20 Products by Frequency
top_products = df['ProductId'].value_counts().head(20)

plt.figure(figsize=(12, 6))
top_products.plot(kind='bar', color='skyblue', edgecolor='black')
plt.xlabel('Product ID')
plt.ylabel('Frequency')
plt.title('Top 20 Most Frequently Ordered Products')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()


# 3. Top 20 Product Families
family_counts = df[df['Family_Id'] != 0]['Family_Id'].value_counts().head(20)

plt.figure(figsize=(12, 6))
family_counts.plot(kind='bar', color='lightcoral', edgecolor='black')
plt.xlabel('Family ID')
plt.ylabel('Frequency')
plt.title('Top 20 Most Frequent Product Families (excluding 0)')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()


# 4. Orders Over Time
orders_by_date = df.groupby('Date')['orderId'].nunique()

plt.figure(figsize=(15, 6))
plt.plot(orders_by_date.index, orders_by_date.values, marker='o', linewidth=2, markersize=4)
plt.xlabel('Date')
plt.ylabel('Number of Orders')
plt.title('Number of Orders Over Time')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()


# 5. Orders by Hour of Day
orders_by_hour = df.groupby('Hour')['orderId'].nunique()

plt.figure(figsize=(12, 6))
plt.bar(orders_by_hour.index, orders_by_hour.values, color='mediumseagreen', edgecolor='black')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Orders')
plt.title('Orders Distribution by Hour of Day')
plt.xticks(range(0, 24))
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()



# 6. Orders by Day of Week
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
orders_by_day = df.groupby('DayOfWeek')['orderId'].nunique()
orders_by_day = orders_by_day.reindex(day_order)

plt.figure(figsize=(12, 6))
plt.bar(orders_by_day.index, orders_by_day.values, color='plum', edgecolor='black')
plt.xlabel('Day of Week')
plt.ylabel('Number of Orders')
plt.title('Orders Distribution by Day of Week')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()



# 7. Revenue by Date
revenue_by_date = df.groupby('Date')['Price'].sum()

plt.figure(figsize=(15, 6))
plt.plot(revenue_by_date.index, revenue_by_date.values, marker='o', linewidth=2, markersize=4, color='orange')
plt.xlabel('Date')
plt.ylabel('Revenue ($)')
plt.title('Total Revenue Over Time')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()


# 8. Customer Analysis - Top 20 Customers by Number of Orders
customer_orders = df.groupby('Account_Id')['orderId'].nunique().sort_values(ascending=False).head(20)

plt.figure(figsize=(12, 6))
customer_orders.plot(kind='bar', color='teal', edgecolor='black')
plt.xlabel('Account ID')
plt.ylabel('Number of Orders')
plt.title('Top 20 Customers by Number of Orders')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()



# 9. Customer Analysis - Top 20 Customers by Total Spending
customer_spending = df.groupby('Account_Id')['Price'].sum().sort_values(ascending=False).head(20)

plt.figure(figsize=(12, 6))
customer_spending.plot(kind='bar', color='gold', edgecolor='black')
plt.xlabel('Account ID')
plt.ylabel('Total Spending ($)')
plt.title('Top 20 Customers by Total Spending')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()



# 10. Products per Order Distribution
products_per_order = df.groupby('orderId').size()

plt.figure(figsize=(12, 6))
plt.hist(products_per_order, bins=50, edgecolor='black', alpha=0.7, color='lightblue')
plt.xlabel('Number of Products per Order')
plt.ylabel('Frequency')
plt.title('Distribution of Products per Order')
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()


# 11. Correlation Heatmap
# Create correlation matrix for numerical columns
corr_data = df[['ProductId', 'Price', 'Family_Id', 'Hour', 'Month']].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_data, annot=True, cmap='coolwarm', center=0, fmt='.2f',
            square=True, linewidths=1, cbar_kws={"shrink": 0.8})
plt.title('Correlation Matrix of Numerical Features')
plt.tight_layout()
plt.show()

"""# Data Summary for ML Model

"""


customer_stats = df.groupby('Account_Id').agg({
    'orderId': 'nunique',
    'Price': 'sum'
})

# Install required libraries for BPR model

"""### ⚠️ Important Note: ALS Model Usage in `implicit` Library

**Correct Usage for ALS:**

The ALS implementation in `implicit` expects **user×item** matrices for both training and inference:


**Key Points:**
- **DO NOT transpose** the matrix for ALS (unlike some other libraries)
- Rows represent users, columns represent items
- For 21,202 users and 24,232 items: shape is **(21202, 24232)**
- The model treats the first dimension as users, second as items

Bước 0: Khởi tạo Spark
"""


from pyspark.sql import SparkSession
import pyspark.sql.functions as F

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("ALS_Recommender_Master_Project") \
    .config("spark.driver.memory", "4g") \
    .getOrCreate()


"""Bước 1: Chuẩn bị Dữ liệu (Aggregation) ⚙️

Dữ liệu 2.5 triệu dòng của bạn là một log giao dịch. Mô hình ALS không đọc được log, nó cần một ma trận (User, Item, Rating). Chúng ta cần tạo ra cột "Rating" ngầm định.

Chúng ta sẽ không dùng Price làm rating. Thay vào đó, chúng ta sẽ đếm số lần mua (purchase_count). Đây là tín hiệu "độ tin cậy" (confidence) của chúng ta. Một người mua 10 lần thì "thích" sản phẩm đó hơn một người mua 1 lần.
"""

user_item_data = list(df[['Account_Id', 'ProductId']].itertuples(index=False, name=None))

columns = ["Account_Id", "ProductId"]
spark_df = spark.createDataFrame(user_item_data, columns)

data_agg = spark_df.groupBy("Account_Id", "ProductId") \
                   .agg(F.count("*").alias("purchase_count"))

data_agg.show()

"""Bước 2: Phân chia Dữ liệu (Train / Validation / Test)"""

(train_data, validation_data, test_data) = data_agg.randomSplit([0.7, 0.15, 0.15], seed=42)


"""Bước 3: Khởi tạo Mô hình ALS

3.1 Defind model
"""



from pyspark.ml.recommendation import ALS
from itertools import product
from pyspark.ml.evaluation import RankingEvaluator


# --- Chuẩn bị "Đáp án" (chỉ làm 1 lần) ---
true_items_val = validation_data \
    .groupBy("Account_Id") \
    .agg(F.collect_list("ProductId").alias("true_items"))

# --- Khởi tạo Thước đo (chỉ làm 1 lần) ---
evaluator = RankingEvaluator(
    metricName="ndcgAtK", k=10,
    labelCol="true_items", predictionCol="pred_items"
)

from pyspark.ml.evaluation import RankingEvaluator
import pyspark.sql.functions as F
from pyspark.sql.types import DoubleType

def calculate_metrics_optimized(model, validation_data, k_values=[10, 15, 20, 25, 30, 35, 40]):
    """
    Optimized: Calculates metrics by generating recommendations ONLY ONCE.
    """
    # 1. Find the max K to generate recommendations just once
    max_k = max(k_values)
    print(f"--- Generating Top-{max_k} recommendations (One-time calc) ---")
    
    # Generate for max_k
    recs = model.recommendForAllUsers(max_k)
    
    # Prepare Ground Truth (AND CAST TO DOUBLE)
    # RankingEvaluator requires Double types for IDs
    true_items_val = validation_data \
        .groupBy("Account_Id") \
        .agg(F.collect_list(F.col("ProductId").cast("double")).alias("true_items"))
    
    # Join Predictions with Ground Truth
    # We cast the predictions array to Double as well
    full_eval_df = recs.select("Account_Id", "recommendations.ProductId") \
        .join(true_items_val, "Account_Id") \
        .select(
            F.col("Account_Id"), 
            F.col("true_items"), 
            F.col("ProductId").cast("array<double>").alias("all_pred_items")
        )
    
    # CRITICAL: Cache this DataFrame so we don't re-compute the join/rec for every K
    full_eval_df.cache()
    
    # Force materialization of cache to ensure speed in loop
    print(f"Cached evaluation data for {full_eval_df.count()} users.")

    metrics_dict = {}

    for k in k_values:
        # 2. Slice the array efficiently using Spark SQL
        # slice(col, start, length) -> Note: Spark SQL arrays are 1-based index
        k_pred_col = F.slice(F.col("all_pred_items"), 1, k)
        
        # Create a temp DF for this specific K
        k_eval_df = full_eval_df.withColumn("prediction_at_k", k_pred_col)

        # 3. Calculate Metrics using Spark Native Evaluators
        
        # NDCG
        ndcg = RankingEvaluator(
            metricName="ndcgAtK", k=k, 
            labelCol="true_items", predictionCol="prediction_at_k"
        ).evaluate(k_eval_df)
        
        # MAP
        map_score = RankingEvaluator(
            metricName="meanAveragePrecisionAtK", k=k,
            labelCol="true_items", predictionCol="prediction_at_k"
        ).evaluate(k_eval_df)
        
        # Precision
        precision = RankingEvaluator(
            metricName="precisionAtK", k=k,
            labelCol="true_items", predictionCol="prediction_at_k"
        ).evaluate(k_eval_df)
        
        # Recall
        recall = RankingEvaluator(
            metricName="recallAtK", k=k,
            labelCol="true_items", predictionCol="prediction_at_k"
        ).evaluate(k_eval_df)

        # 4. Calculate Coverage and HitRate manually
        # These metrics require collecting all items, so we convert to pandas for calculation
        eval_pd = k_eval_df.select("Account_Id", "true_items", "prediction_at_k").toPandas()
        
        total_hits = 0
        total_users = len(eval_pd)
        all_recommended_items = set()
        all_items = set()
        
        for _, row in eval_pd.iterrows():
            true_set = set(row['true_items'])
            pred_set = set(row['prediction_at_k'])
            all_items.update(true_set)
            all_recommended_items.update(pred_set)
            
            # Count hits (items that are both recommended and in true items)
            if len(pred_set) > 0:
                hits = len(true_set & pred_set)
                if hits > 0:
                    total_hits += 1  # User has at least one hit
        
        # HitRate: proportion of users who have at least one hit
        hit_rate = total_hits / total_users if total_users > 0 else 0
        
        # Coverage: proportion of all items in catalog that are recommended
        coverage = len(all_recommended_items) / len(all_items) if len(all_items) > 0 else 0

        metrics_dict[k] = {
            'precision': precision,
            'recall': recall,
            'map': map_score,
            'ndcg': ndcg,
            'coverage': coverage,
            'hitRate': hit_rate
        }
        
        print(f"METRIC|k={k}|precision={precision:.4f}|recall={recall:.4f}|map={map_score:.4f}|ndcg={ndcg:.4f}|coverage={coverage:.4f}|hitRate={hit_rate:.4f}")

    # Clean up memory
    full_eval_df.unpersist()
    
    return metrics_dict
ranks = [10]
regParams = [0.01]
alphas = [1]
maxIters = [10]

best_model = None
best_ndcg = -1

true_items_val = validation_data \
    .groupBy("Account_Id") \
    .agg(F.collect_list("ProductId").alias("true_items"))

def train_and_eval(rank, regParam, alpha, maxIter, versionTag):
    als = ALS(
        userCol="Account_Id",
        itemCol="ProductId",
        ratingCol="purchase_count",

        # rank=r,
        # regParam=reg,
        # alpha=a,
        # coldStartStrategy="drop"

        # --- (Hyperparameters)

        # 1. implicitPrefs (Quyết định Hàm Loss/Tối ưu hóa)
        # Phải = True. Báo cho ALS biết: "Đây là dữ liệu ngầm định.
        # Hãy dùng hàm loss W-RMSE, không phải RMSE.
        # Hãy hiểu rằng "purchase_count" là "confidence", không phải "rating".
        implicitPrefs=True,

        # 2. rank (Độ phức tạp của mô hình)
        # Số lượng yếu tố tiềm ẩn (latent factors).
        # Quá nhỏ (ví dụ: 5) -> Underfitting (học dốt)
        # Quá lớn (ví dụ: 100) -> Overfitting (học vẹt)
        rank=rank,

        # 3. regParam (Điều chuẩn - "Liều thuốc" chữa Overfitting)
        # "Phạt" mô hình nếu nó học vẹt.
        # Đây là tham số bạn sẽ "tune" nhiều nhất trên tập Validation.
        regParam=regParam,

        # 4. alpha ("Bộ khuếch đại" Confidence)
        # Khuếch đại sự khác biệt giữa "mua 1 lần" và "mua 50 lần".
        # Như đã ví dụ: 1 + (alpha * purchase_count)
        alpha=alpha, # Giá trị 40 là mặc định tốt cho e-commerce

        # 5. maxIter (Số vòng lặp tối ưu hóa)
        # Số lần "đi xuống núi".
        maxIter=maxIter,

        # --- Các cài đặt khác ---
        coldStartStrategy="drop" # Bỏ qua user/item mới khi đánh giá

    )
    model = als.fit(train_data)

    print("💾 SAVING MODEL TO DATABASE")
    print("="*80)

    # Calculate and log all metrics
    print("="*80)
    print("CALCULATING METRICS")
    print("="*80)
    metrics_dict = calculate_metrics_optimized(model, validation_data)
    
    # Also keep the old NDCG@10 log for backward compatibility
    if 10 in metrics_dict:
        ndcg_10 = metrics_dict[10]['ndcg']
        print(f"Kết quả (Validation) NDCG@10 = {ndcg_10:.4f} {rank}, {regParam}, {alpha}, {maxIter}")

    # Save model to database
    print("="*80)
    print("💾 SAVING MODEL TO DATABASE")
    print("="*80)
    try:
        from database import SessionLocal, ModelVersion
        
        # Save model to temporary directory (will be deleted after zipping)
        temp_model_dir = tempfile.mkdtemp()
        temp_model_path = os.path.join(temp_model_dir, f"als_model_{versionTag}")
        
        # Save model to temp directory
        model.write().overwrite().save(temp_model_path)
        print(f"✅ Model saved to temporary directory: {temp_model_path}")
        
        # Create a zip file of the model directory
        temp_zip = tempfile.NamedTemporaryFile(delete=False, suffix='.zip')
        temp_zip_path = temp_zip.name
        temp_zip.close()
        
        with zipfile.ZipFile(temp_zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files in os.walk(temp_model_path):
                for file in files:
                    file_path = os.path.join(root, file)
                    # Store relative path in zip
                    arcname = os.path.relpath(file_path, temp_model_path)
                    zipf.write(file_path, arcname)
        
        # Read zip file as binary
        with open(temp_zip_path, 'rb') as f:
            model_data = f.read()
        
        # Clean up temporary files and directories
        os.unlink(temp_zip_path)
        shutil.rmtree(temp_model_dir)
        print(f"✅ Cleaned up temporary files")
        
        # Save to database
        db = SessionLocal()
        try:
            # Check if model version already exists
            existing_version = db.query(ModelVersion).filter(
                ModelVersion.version_tag == versionTag
            ).first()
            
            if existing_version:
                # Update existing version
                existing_version.model_data = model_data
                existing_version.artifact_path = None  # No disk path since we're not saving to disk
                print(f"✅ Updated existing model version in database: {versionTag}")
            else:
                # Create new model version
                model_version = ModelVersion(
                    version_tag=versionTag,
                    artifact_path=None,  # No disk path since we're not saving to disk
                    model_data=model_data,
                    project_id=1,
                    isActive=False
                )
                db.add(model_version)
                print(f"✅ Saved new model version to database: {versionTag}")
            
            db.commit()
            print(f"  • Model size: {len(model_data) / (1024*1024):.2f} MB")
            print(f"  • Database storage: PostgreSQL")
        except Exception as db_error:
            db.rollback()
            print(f"❌ Error saving model to database: {db_error}")
            raise
        finally:
            db.close()
    except ImportError as import_error:
        print(f"⚠️ Warning: Could not import database module: {import_error}")
        print("   Please ensure database.py is available.")
    except Exception as e:
        print(f"⚠️ Warning: Error saving model to database: {e}")


if __name__ == "__main__":
    import argparse
    
    # Set up argument parser
    parser = argparse.ArgumentParser(description='ALS Recommender System Training')
    parser.add_argument('--rank', type=int, default=10, help='Number of latent factors (default: 10)')
    parser.add_argument('--regParam', type=float, default=0.01, help='Regularization parameter (default: 0.01)')
    parser.add_argument('--alpha', type=float, default=1, help='Confidence amplification factor (default: 1)')
    parser.add_argument('--maxIter', type=int, default=10, help='Maximum number of iterations (default: 10)')
    parser.add_argument('--versionTag', type=str, default=datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S"), help='Version tag for saving the model (e.g., a timestamp)')
    # Parse arguments
    args = parser.parse_args()
    
    # Extract values
    rank = args.rank
    regParam = args.regParam
    alpha = args.alpha
    maxIter = args.maxIter
    versionTag = args.versionTag
   
    print(f"Version tag: {versionTag}")
    # Train and evaluate model
    train_and_eval(rank, regParam, alpha, maxIter, versionTag)

